In [1]:
# importing the dependencies
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [3]:
# dataset loading and data preprocessing
credit_card_data = pd.read_csv(r"C:\Users\my hp\Downloads\Project_10_Credit_Card_Fraud_Detection\creditcard.csv")

In [4]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [5]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [6]:
credit_card_data.shape

(284807, 31)

In [7]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [8]:
credit_card_data.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,3.918649e-15,5.682686e-16,-8.761736e-15,2.811118e-15,-1.552103e-15,2.040130e-15,-1.698953e-15,-1.893285e-16,-3.147640e-15,...,1.473120e-16,8.042109e-16,5.282512e-16,4.456271e-15,1.426896e-15,1.701640e-15,-3.662252e-16,-1.217809e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

In [9]:
credit_card_data['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [10]:
# dataset higlhly unbalanced : 0 for normal transaction, 1 for fraudulent transaction
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [11]:
# checking the statistical measurements of the data
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [13]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [14]:
# compare the values for both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [16]:
# Under sampling data, building a sample dataset containing similar legit and fraud transactions
# no. of fraudulent transactions = 492
legit_sample = legit.sample(n=492)

In [17]:
# concatenating the datasets
new_dataset = pd.concat([legit_sample,fraud],axis=0)
new_dataset

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
74791,55756.0,1.222118,-0.054932,0.645684,0.761856,-0.760569,-0.691848,-0.194021,-0.038620,0.710121,...,-0.313973,-0.796030,0.093215,0.391167,0.276659,0.289391,-0.030922,0.013628,9.00,0
229606,145987.0,-7.340418,6.154077,-5.010672,-1.441771,-2.160314,-1.442937,-1.038595,2.580050,3.400090,...,-1.012930,-1.166950,0.355808,0.556497,0.568209,-0.067666,-0.717721,-1.547317,17.99,0
91805,63635.0,0.145186,0.411510,1.102774,0.650531,-0.220104,0.127391,0.079178,0.268993,0.123013,...,0.168984,0.741704,0.119917,0.268892,-1.204778,0.304542,0.196130,0.154221,1.87,0
134017,80610.0,1.030574,-0.923318,-0.391228,-0.678770,-0.449453,-0.064321,-0.093532,0.012561,-1.388969,...,-0.224262,-0.469558,-0.071921,-0.245349,0.189614,1.100662,-0.089046,0.002023,148.53,0
121346,76157.0,1.020244,-0.303081,1.215219,1.620950,-0.737809,0.907879,-0.687964,0.481975,1.129959,...,-0.369529,-0.687157,0.075466,0.000682,0.361965,-0.524817,0.079904,0.018034,18.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [18]:
new_dataset.shape

(984, 31)

In [19]:
new_dataset['Class'].value_counts()

0    492
1    492
Name: Class, dtype: int64

In [21]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94324.691057,-0.136986,0.075419,-0.062223,-0.031810,-0.045693,0.126076,-0.046168,-0.020721,-0.024081,...,0.002348,-0.017624,0.013316,-0.025028,-0.024399,0.023003,-0.016468,-0.011891,0.026102,94.016931
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [22]:
# splitting the data into features and targets
X = new_dataset.drop(columns = 'Class', axis = 1)
Y = new_dataset['Class']

In [23]:
X, Y

(            Time        V1        V2        V3        V4        V5        V6  \
 74791    55756.0  1.222118 -0.054932  0.645684  0.761856 -0.760569 -0.691848
 229606  145987.0 -7.340418  6.154077 -5.010672 -1.441771 -2.160314 -1.442937
 91805    63635.0  0.145186  0.411510  1.102774  0.650531 -0.220104  0.127391
 134017   80610.0  1.030574 -0.923318 -0.391228 -0.678770 -0.449453 -0.064321
 121346   76157.0  1.020244 -0.303081  1.215219  1.620950 -0.737809  0.907879
 ...          ...       ...       ...       ...       ...       ...       ...
 279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
 280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
 280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
 281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
 281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

               V7        V8        V9  ...       V20       V21       V22  \
 74791  -0.194021 -0.038620  0.710121  ... -0.177290 -0.313973 -0.796030
 229606 -1.038595  2.580050  3.400090  ...  2.049554 -1.012930 -1.166950
 91805   0.079178  0.268993  0.123013  ... -0.165531  0.168984  0.741704
 134017 -0.093532  0.012561 -1.388969  ... -0.288978 -0.224262 -0.469558
 121346 -0.687964  0.481975  1.129959  ... -0.239626 -0.369529 -0.687157
 ...          ...       ...       ...  ...       ...       ...       ...
 279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
 280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
 280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
 281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
 281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

              V23       V24       V25       V26       V27       V28  Amount
 74791   0.093215  0.391167  0.276659  0.289391 -0.030922  0.013628    9.00
 229606  0.355808  0.556497  0.568209 -0.067666 -0.717721 -1.547317   17.99
 91805   0.119917  0.268892 -1.204778  0.304542  0.196130  0.154221    1.87
 134017 -0.071921 -0.245349  0.189614  1.100662 -0.089046  0.002023  148.53
 121346  0.075466  0.000682  0.361965 -0.524817  0.079904  0.018034   18.99
 ...          ...       ...       ...       ...       ...       ...     ...
 279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
 280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
 280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
 281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
 281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

 [984 rows x 30 columns],
 74791     0
 229606    0
 91805     0
 134017    0
 121346    0
          ..
 279863    1
 280143    1
 280149    1
 281144    1
 281674    1
 Name: Class, Length: 984, dtype: int64)

In [24]:
# splitting the data into training and testing data
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [25]:
X.shape, X_train.shape, X_test.shape

((984, 30), (787, 30), (197, 30))

In [27]:
# model training : Logistic Regression
model = LogisticRegression()

In [28]:
model.fit(X_train, Y_train)

E:\photos\ANACONDA\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [29]:
# model evaluation - prediction on training data
X_train_pred = model.predict(X_train)
# accuracy on training data
training_data_accuracy = accuracy_score(Y_train, X_train_pred)
training_data_accuracy

0.9466327827191868

In [30]:
# prediction on testing data
X_test_pred = model.predict(X_test)
# accuracy on testing data
test_data_accuracy = accuracy_score(Y_test, X_test_pred)
test_data_accuracy

0.9289340101522843

In [33]:
#classification report
from sklearn import metrics
Y_pred = model.predict(X_test)
cr = metrics.classification_report(Y_test, Y_pred)
cr

'              precision    recall  f1-score   support\n\n           0       0.90      0.96      0.93        99\n           1       0.96      0.90      0.93        98\n\n    accuracy                           0.93       197\n   macro avg       0.93      0.93      0.93       197\nweighted avg       0.93      0.93      0.93       197\n'

In [34]:
score_1 = metrics.r2_score(Y_pred,Y_test)
score_1

0.7144927536231884

In [35]:
mae = metrics.mean_absolute_error(Y_pred,Y_test)
mae

0.07106598984771574

In [36]:
cm = metrics.confusion_matrix(Y_pred,Y_test)
cm

array([[95, 10],
       [ 4, 88]], dtype=int64)